defaults:
  - img: flower_16bit
  - mlp: siren
  - optim: adam
  - hydra # hydra stuff
  - override hydra/launcher: basic_launcher
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

exp_name: ${mlp.name}_${img.name}
seed: 0
device: cuda # cpu or cuda

entropy_coding: {}
masking: {}
quant: {}

train:
  num_steps: 2000
  log_steps: 400
  batch_height: ${img.height}
  batch_width: ${img.width}
  save_weights: True
  multiplier: 1   # for extended training
  mixed_precision: True  # Using pytorch's amp

wandb:
  use: True
  entity: implicit-image
  project: siren-basic
  api_key: ${hydra:runtime.cwd}/wandb_api.key
  name: ${exp_name}
