defaults:
  - img: flower_16bit
  - hydra
  - mlp: siren
  - optim: adam
  - override hydra/launcher: basic_launcher
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

exp_name: ${mlp.name}_${img.name}
seed: 0
device: cuda # cpu or cuda


train:
  log_iters: 100
  num_steps: 2000
  batch_height: ${img.height}
  batch_width: ${img.width}
  save_weights: False
  multiplier: 1
  mixed_precision: False

quant: {}
masking: {}

wandb:
  use: True
  entity: implicit-image
  project: siren-basic
  api_key: ${hydra:runtime.cwd}/wandb_api.key
  name: ${exp_name}
